spring.datasource.url=jdbc:mysql://localhost:3306/web

spring.datasource.username=root
spring.datasource.password=20032003

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=ajD82js9Dkd82js9Dkd82Jd9s8Fjs9Fjs8Fjs1Dks9Dks9Fjs0Dks
api.prefix: api

minio.url=https://minio1.webtui.vn:9000
minio.bucket=bucket-xungdeptry
minio.accessKey=xungdeptry
minio.secretKey=20032003

webhook.apiKey=120220032015A@a
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jackson.mapper.accept-case-insensitive-enums=true

google.client-id:777794922407-knmfkv6c29521061f2gccmfn0cvbt8j4.apps.googleusercontent.com
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false

partnerId=24723774290
partnerKey=5454dbee1dec05a4cd368a9ab511e843
urlApiCharging=https://doithe1s.vn/chargingws/v2

# SMTP
spring.mail.host=smtp.your-provider.com
spring.mail.port=587
spring.mail.username=xunglord@gmail.com
spring.mail.password=20032003A@a

# TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=false

# App mail defaults
app.mail.from=no-reply@yourdomain.com
app.mail.fromName=Mini Ecom

# Async pool (tu\u1ef3 ch\u1ecdn)
app.mail.async.corePoolSize=4
app.mail.async.maxPoolSize=8
app.mail.async.queueCapacity=500