spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

jwt:
  secret: ${JWT_KEY}

app:
  upload-dir: /opt/apps/miniEcom/uploads
  mail:
    from: ${APP_MAIL_FROM}

baseUrl:
  web: https://xunglord.com

webhook:
  apiKey: ${WEBHOOK_KEY}

google:
  client-id: ${GOOGLE_CLIENT_ID}

partnerId: ${PARTNER_ID}
partnerKey: ${PARTNER_KEY}

minio:
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}