spring.datasource.url=jdbc:mysql://localhost:3306/web

spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret= ${JWT_KEY}
api.prefix: api

#storage

app.storage=local
app.upload-dir= G:/MINI-E-Commerce/uploads
app.upload-url-prefix=/uploads

minio.url=https://minio1.webtui.vn:9000
minio.bucket=bucket-xungdeptry
minio.accessKey=${MINIO_ACCESS_KEY}
minio.secretKey=${MINIO_SECRET_KEY}

baseUrl.web = http://localhost:4200

#webhook

webhook.apiKey=${WEBHOOK_KEY}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jackson.mapper.accept-case-insensitive-enums=true
#login_google
google.client-id:${GOOGLE_CLIENT_ID}
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false

#
partnerId=${PARTNER_ID}
partnerKey=${PARTNER_KEY}
urlApiCharging=https://doithe1s.vn/chargingws/v2

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=false

# App mail defaults
app.mail.from=${APP_MAIL_FROM}
app.mail.fromName=XungLord.com

# Async pool (tu\u1ef3 ch\u1ecdn)
app.mail.async.corePoolSize=4
app.mail.async.maxPoolSize=8
app.mail.async.queueCapacity=500

